# Configuration script to Travis-CI
arch:
     - amd64
     - ppc64le
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pipenv coveralls[yaml]
  - pipenv sync --dev
script:
  - pipenv run pytest --cov src/ofxstatement
  - pipenv run black --check setup.py src
  - pipenv run mypy src
after_success:
  coveralls
